name: picky_lk
description: A new Flutter project.

publish_to: "none"

# version number of the app
version: 1.0.0+1

# flutter sdk for the project
environment:
  sdk: ">=3.0.5 <4.0.0"

# release dependencies
dependencies:
  # for icons
  cupertino_icons: ^1.0.2
  
  # for the bottom navigation bar
  curved_navigation_bar: ^1.0.1

  # flutter sdk
  flutter:
    sdk: flutter

  # for routes and state management
  get: ^4.6.5

# tempry dependencies
dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  # images
  assets:
    - assets/images/
